name: Continuous Deployment

on:
    push:
        branches:
            - 'main'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true
    
jobs:

    dev:
        uses: srinivas-kujala/databricks-workflows/.github/workflows/deploy.yml@main
        with:
            branch-name: ${{ github.ref_name }}
            environment: 'dev'
        secrets: inherit
    
    qa:
        needs: dev
        uses: srinivas-kujala/databricks-workflows/.github/workflows/deploy.yml@main
        with:
            branch-name: ${{ github.ref_name }}
            environment: 'qa'
        secrets: inherit

    release:
        needs: qa
        uses: srinivas-kujala/databricks-workflows/.github/workflows/deploy.yml@main
        with:
            branch-name: ${{ github.ref_name }}
            environment: 'release'
        secrets: inherit
    
    prod:
        needs: release
        uses: srinivas-kujala/databricks-workflows/.github/workflows/deploy.yml@main
        with:
            branch-name: ${{ github.ref_name }}
            environment: 'prod'
        secrets: inherit
