name: On Demand Build

on:
    workflow_dispatch:
        inputs:
            branch-name:  # id of input
                type: string
                description: 'Name of the repository branch. Ex: feature/12345_Title-Of-Ticket'
                required: true
                default: main
            environment:  # id of input
                type: choice
                description: 'Please select Environment for deployment'
                default: dev
                options:
                    - 'dev'
                    - 'qa'
                    - 'release'
                    - 'prod'

concurrency:
    group: ${{ github.workflow }}-${{ inputs.branch-name }}
    cancel-in-progress: true
    
jobs:

    deploy:
        uses: srinivas-kujala/databricks-workflows/.github/workflows/deploy.yml@main 
        with:
            branch-name: ${{ inputs.branch-name }}
            environment: ${{ inputs.environment }}
        secrets: inherit
